version: '3.9'

services:
  catalog-service-db:
    image: postgres:16
    container_name: catalog-service-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: catalog_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - catalog_service_db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user_service_user -d user_service_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  catalog_service_db_data: